# Generated by Django 3.2.8 on 2021-10-21 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=256, null=True, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=256, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Emali')),
                ('photo', models.CharField(max_length=256, verbose_name='Photo')),
                ('about', models.TextField(verbose_name='About')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('desc', models.TextField(verbose_name='Description')),
                ('membersID', models.ManyToManyField(related_name='teams_members', to='tasks_api.Member')),
            ],
        ),
    ]
