# Generated by Django 3.2.8 on 2021-10-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='team',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update At'),
        ),
        migrations.AlterField(
            model_name='member',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update At'),
        ),
    ]
