# Generated by Django 3.2.8 on 2021-10-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0002_auto_20211021_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='membersID',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
