# Generated by Django 3.2.8 on 2021-10-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0005_auto_20211026_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstage',
            name='stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('completed', 'Completed')], max_length=20, verbose_name='Stages'),
        ),
    ]
