# Generated by Django 3.2.8 on 2021-10-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0007_alter_taskstage_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstage',
            options={'ordering': ('-order',)},
        ),
        migrations.AddField(
            model_name='taskstage',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Order'),
        ),
    ]
