# Generated by Django 3.2.8 on 2021-10-27 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0010_auto_20211027_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='stage',
        ),
        migrations.AddField(
            model_name='taskstage',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks_api.task'),
        ),
    ]
