# Generated by Django 3.2.8 on 2021-10-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0013_alter_task_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(null=True, verbose_name='order'),
        ),
    ]
