# Generated by Django 3.2.8 on 2021-10-29 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0015_auto_20211029_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstage',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='tasks_api.taskstage'),
        ),
    ]
