# Generated by Django 3.2.8 on 2021-11-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0016_auto_20211029_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('color', models.CharField(max_length=256, verbose_name='Color')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(related_name='labels', to='tasks_api.Label'),
        ),
    ]
