# Generated by Django 3.2.8 on 2021-11-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0017_auto_20211102_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ('label',)},
        ),
        migrations.RemoveField(
            model_name='label',
            name='color',
        ),
        migrations.RemoveField(
            model_name='label',
            name='title',
        ),
        migrations.AddField(
            model_name='label',
            name='colorl',
            field=models.CharField(default='green', max_length=256, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='label',
            name='label',
            field=models.CharField(default='Normal', max_length=256, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='label',
            name='value',
            field=models.CharField(default='normal', max_length=256, verbose_name='Value'),
        ),
    ]
