# Generated by Django 3.2.8 on 2021-11-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0019_auto_20211103_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='colorl',
            new_name='color',
        ),
    ]
