# Generated by Django 3.2.8 on 2021-11-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0022_auto_20211108_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='teams'),
        ),
    ]
