# Generated by Django 3.2.8 on 2021-11-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0023_alter_team_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='members', to='tasks_api.Member'),
        ),
    ]
