# Generated by Django 3.2.8 on 2021-11-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0025_alter_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='teams'),
        ),
    ]
