# Generated by Django 3.2.8 on 2021-11-16 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks_api', '0027_alter_team_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_to',
            field=models.DateField(null=True, verbose_name='Due to'),
        ),
    ]
