# Generated by Django 3.2.8 on 2021-12-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0032_auto_20211207_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='about',
            field=models.TextField(max_length=500, null=True, verbose_name='About'),
        ),
    ]
