# Generated by Django 3.2.8 on 2021-12-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0033_alter_member_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.CharField(max_length=256, null=True, verbose_name='Avatar URL'),
        ),
    ]
